### ISSUE TITLE
Laravel Breeze tidak mau di install

### ISSUE THREAD

**Issue by hanifarsyaha** [taufanfadhilah/laracamp#3]
permisi mas, saya mau nanya. saya terkendala di laravel breeze saya tdk mau di install, errornya karna versi php saya 8.0, gmana ya mas solusi nya?
![image](https://user-images.githubusercontent.com/103974947/175202375-07e07e08-b7bb-4fd7-a828-26704d32ea22.png)

**Comment by taufanfadhilah** [comment]
@hanifarsyaha  kalau dilihat dari errornya, itu butuh di downgrade karena Laravel yang terinstall memerlukan php 7.3
