### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'users_id' doesn't have a default value

### ISSUE THREAD

**Issue by nasawiko** [taufanfadhilah/laracamp#4]
Tidak bisa input data, dengan kasus sebagai berikut:
1. Errornya
![image](https://user-images.githubusercontent.com/53363127/175227140-9e61fc5f-c1ed-43f0-978a-eff043015239.png)

2. phone number, detail pesanan, users_id, menus_id dan admin number masuk ke chekouts (chekouts Controller)
![image](https://user-images.githubusercontent.com/53363127/175227549-e5d6cf61-9347-4877-bc2d-8f00f1c93946.png)

3. Validasi dari requestnya
![image](https://user-images.githubusercontent.com/53363127/175227697-b0320670-8d03-43dd-bd6f-1eb711760dcd.png)

4. Run $datanya dapat semua 
![image](https://user-images.githubusercontent.com/53363127/175228241-d38ea8e7-20c2-43ec-870d-92e903a2416f.png)
![image](https://user-images.githubusercontent.com/53363127/175228264-935a014b-39ef-4584-9e44-7f95ce2cbc98.png)

**Comment by nasawiko** [comment]
Semoga bisa ke solve, bingung udah 2 hari, ngejar skripsian mas T_T

**Comment by taufanfadhilah** [comment]
@nasawiko coba check di model checkout, sudah ada fillable **users_id** belum?

**Comment by nasawiko** [comment]
@taufanfadhilah sip solve mas, alhamdulillah bisa lanjut skripsian haha
